<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <None Include="wwwroot\images\pictureportfolio.png" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="wwwroot\images\loan\" />
      <Folder Include="wwwroot\images\visualdesign\" />
      <Folder Include="wwwroot\files\" />
    </ItemGroup>

</Project>
